### ISSUE TITLE
[Bug]: Your part 2 code for day 2 doesnt work for my input (input in description)

### ISSUE THREAD

**Issue by wojpo** [Norbiros/AoC2024#1]
[message (1).txt](https://github.com/user-attachments/files/17984081/message.1.txt)

**Comment by Norbiros** [comment]
Thanks for noticing! My previous solution was greedy, which caused an error for the input `49 47 44 45 44` (it marked 45 as an error). I could have used a normal approach (remove one by one and check), but that wouldn't have been as interesting, so I opted for dynamic programming. It’s still O(n) but works for all inputs :3
